on:
  push:
    branches:
      - main

name: Deployment

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: yarn --frozen--lockfile

    - name: Build
      run: yarn run build

    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local_path: ${{ secrets.LOCAL_PATH }}
        remote_path: ${{ secrets.REMOTE_PATH }}
        args: -o ConnectTimeout=5
